#!/bin/bash

docker build --build-arg VCS_REF=`git rev-parse — short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
	${VERSION:+--build-arg "VERSION=$VERSION"} \
  -t $IMAGE_NAME .
